pessoa = {'nome': 'Prof(a) Ana', 'idade': 33, 'cursos':['Ingles', 'Portugues']}
# print(type(pessoa))
# print(dir(pessoa))
# print(help(pessoa))
print(pessoa)
print(pessoa['nome'])
print(pessoa['idade'])
print(pessoa['cursos'])
print(pessoa['cursos'][0])
print(pessoa['cursos'][1])
# print(pessoa['cursos'][2])
print(pessoa.keys())
print(pessoa.values())
print(pessoa.items())
print(pessoa.get('idade'))
print(pessoa.get('tags'))
print(pessoa.get('tags', []))
